name: hexo GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          wget https://github.com/jgm/pandoc/releases/download/2.18/pandoc-2.18-1-amd64.deb
          sudo dpkg -i pandoc-2.18-1-amd64.deb 

      - name: Install and Build  
        run: |
          npm uninstall *
          npm install -g hexo-cli 
          npm install  
          hexo clean & hexo g

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          personal_token: ${{ secrets.HEXO_TOKEN }}
          publish_dir: ./public
          publish_branch: main	# 发布到哪个branch
          external_repository: lwmfjc/lwmfjc.github.io	# 发布到哪个repo